#********************************************************************************
# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#*******************************************************************************/

[workspace]

resolver = "2"

members = [
    "databroker",
    "databroker-cli",
    "databroker-grpc",
    "databroker-proto",
    "kuksa",
    "kuksa-grpc",
    "kuksa-proto",
]

exclude = [
   "lib/*"
]

[workspace.dependencies]
clap = { version = "4.2", default-features = false }
databroker-grpc = { path = "databroker-grpc" }
databroker-proto = { path = "databroker-proto" }
kuksa = { path = "kuksa" }
kuksa-grpc = { path = "kuksa-grpc" }
kuksa-proto = { path = "kuksa-proto" }
# prost has no features
prost = "0.11"
# prost-types has no features
prost-types = "0.11"
thiserror = "1.0.47"
# tokio does not enable features by default
tokio = "1.17.0"
# tokio-stream has no features
tokio-stream = "0.1.8"
tonic = { version = "0.9.1", default-features = false }
tonic-build = { version = "0.8", default-features = false }

[profile.release]
lto = true                 # Link time optimization (dead code removal etc...)
opt-level = "s"
codegen-units = 1
incremental = false
strip = true
# debug = true               # for profiling (turn off otherwise)
# split-debuginfo = "packed" # only enable when `debug = true``
